name: Build Failure Report
description: Report unexpected build failures with the project
body:
  - type: input
    id: subproject
    attributes:
      label: Is this an issue with the Amazon Chime SDK for C++ or with the Amazon Chime SDK for C++ Signaling Client?
    validations:
      required: true
  - type: checkboxes
    id: existing-resources-check
    attributes:
      label: Have you reviewed our existing documentation?
      description: Please check all resources as your issue may have been addressed before.
      options:
      - label: GitHub [issues](https://github.com/aws/amazon-chime-sdk-cpp/issues)
        required: true
  - type: input
    id: platforms
    attributes:
      label: What Windows version are you seeing the problem on?
    validations:
      required: true
  - type: textarea
    id: build-command
    attributes:
      label: Build setup
      description: How are you currently linking the Windows binary?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Amazon Chime SDK for C++ Windows Binary version
      description: What version of our Amazon Chime SDK for C++ Windows Binary are you trying to build?
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Log
      description: Please provide the error. If possible, attach the entire build log to the issue after posting.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!